server:
  port: 8120 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  #spring:
  redis:
    host: yourserverip
    port: yourredisport
    database: 0
    password: "yourpassword" #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  cloud:
    nacos:
      discovery:
        server-addr: yourserverip:8848 # nacos服务地址
    sentinel:
      transport:
        dashboard: yourserverip:yoursentineldashboardip

  rabbitmq:
    host: yourserverip
    port: 5672
    virtual-host: yourvirtrulhost
    username: root
    password: "yourpassword"

#自定义容联云配置信息，方便统一修改
ronglianyun:
  sms:
    server-ip: "app.cloopen.com"
    server-port: "8883"
    account-s-id: "yourcloopenid"
    account-token: "yourcloopentoken"
    app-id: "8aaf070882ede8b3018312f084e2062c"
    template-id: "1"

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  #开启Feign对Sentinel的支持
  sentinel:
    enabled: true
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数

logging:
  level:
    com.lin.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口

